name: Deploy SDP_WEB_WorkCalendar (Nuxt) with PM2

on:
  push:
    branches:
      - Deploy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Prisma generate
        run: npx prisma generate
      - name: Build project
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: .output

  deploy:
    needs: build
    runs-on: ['self-hosted', 'TDP-IMMIGRATION']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Copy build to IIS folder
        run: |
          if exist C:\inetpub\wwwroot\Work_Calendar\prd rmdir /s /q C:\inetpub\wwwroot\Work_Calendar\prd
          xcopy .output C:\inetpub\wwwroot\Work_Calendar\prd /E /I /Y
      - name: Start/Restart PM2
        run: |
          cd C:\inetpub\wwwroot\Work_Calendar
          pm2 startOrRestart ecosystem.config.cjs --env production
          pm2 save
